sudo: required
services:
  - docker
language: python
python:
  - "3.4"
  - "3.5"
env:
  - COMPOSE_VERSION: 1.4.1
before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - cd tests/data/ && docker-compose up -d
 - cd ../../
install:
  - pip install coveralls
script:
  - sleep 5
  - coverage run setup.py test
after_success:
  coveralls
notifications:
  email:
    - alexey.dubkov@gmail.com
    - maksim77ster@gmail.com
